### ISSUE TITLE
Format tag name [tag name] by [company name]

### ISSUE THREAD

**Issue by philpott** [addingwell/meta-conversion-api-tag#6]
Please update your tag's name to match the format of [tag name] by [company name] since this is not your own company's tag template.

Thanks

**Comment by lucasgtm** [comment]
Hello Michael,

I'm not sure to understand why do we need to change the tag name to add our company name as the company name appears in the `brand.displayName` field.

Example with another tag we developed:
<img src="https://github.com/user-attachments/assets/be5c9e6b-b678-460a-8167-6da7da9c6f5c" width="400">

Thank you for your answer.
Lucas

**Comment by jhuret** [comment]
The template name has been updated according to this format: [tag name] by [company name].
